/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.meera.multidatasource.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import com.meera.multidatasource.model.TableFromDefaultDataSource;
import com.meera.multidatasource.model.TableFromDefaultDataSourceModel;
import com.meera.multidatasource.model.TableFromDefaultDataSourceSoap;

import java.io.Serializable;

import java.sql.Types;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * The base model implementation for the TableFromDefaultDataSource service. Represents a row in the &quot;meera_TableFromDefaultDataSource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.meera.multidatasource.model.TableFromDefaultDataSourceModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TableFromDefaultDataSourceImpl}.
 * </p>
 *
 * @author E5410
 * @see TableFromDefaultDataSourceImpl
 * @see com.meera.multidatasource.model.TableFromDefaultDataSource
 * @see com.meera.multidatasource.model.TableFromDefaultDataSourceModel
 * @generated
 */
@JSON(strict = true)
public class TableFromDefaultDataSourceModelImpl extends BaseModelImpl<TableFromDefaultDataSource>
	implements TableFromDefaultDataSourceModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a table from default data source model instance should use the {@link com.meera.multidatasource.model.TableFromDefaultDataSource} interface instead.
	 */
	public static final String TABLE_NAME = "meera_TableFromDefaultDataSource";
	public static final Object[][] TABLE_COLUMNS = {
			{ "IFDDSId", Types.BIGINT },
			{ "Description", Types.VARCHAR }
		};
	public static final String TABLE_SQL_CREATE = "create table meera_TableFromDefaultDataSource (IFDDSId LONG not null primary key,Description VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table meera_TableFromDefaultDataSource";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.meera.multidatasource.model.TableFromDefaultDataSource"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.meera.multidatasource.model.TableFromDefaultDataSource"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static TableFromDefaultDataSource toModel(
		TableFromDefaultDataSourceSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		TableFromDefaultDataSource model = new TableFromDefaultDataSourceImpl();

		model.setIFDDSId(soapModel.getIFDDSId());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<TableFromDefaultDataSource> toModels(
		TableFromDefaultDataSourceSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<TableFromDefaultDataSource> models = new ArrayList<TableFromDefaultDataSource>(soapModels.length);

		for (TableFromDefaultDataSourceSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.meera.multidatasource.model.TableFromDefaultDataSource"));

	public TableFromDefaultDataSourceModelImpl() {
	}

	public long getPrimaryKey() {
		return _IFDDSId;
	}

	public void setPrimaryKey(long primaryKey) {
		setIFDDSId(primaryKey);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_IFDDSId);
	}

	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	public Class<?> getModelClass() {
		return TableFromDefaultDataSource.class;
	}

	public String getModelClassName() {
		return TableFromDefaultDataSource.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("IFDDSId", getIFDDSId());
		attributes.put("Description", getDescription());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long IFDDSId = (Long)attributes.get("IFDDSId");

		if (IFDDSId != null) {
			setIFDDSId(IFDDSId);
		}

		String Description = (String)attributes.get("Description");

		if (Description != null) {
			setDescription(Description);
		}
	}

	@JSON
	public long getIFDDSId() {
		return _IFDDSId;
	}

	public void setIFDDSId(long IFDDSId) {
		_IFDDSId = IFDDSId;
	}

	@JSON
	public String getDescription() {
		if (_Description == null) {
			return StringPool.BLANK;
		}
		else {
			return _Description;
		}
	}

	public void setDescription(String Description) {
		_Description = Description;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			TableFromDefaultDataSource.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public TableFromDefaultDataSource toEscapedModel() {
		if (_escapedModelProxy == null) {
			_escapedModelProxy = (TableFromDefaultDataSource)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelProxyInterfaces,
					new AutoEscapeBeanHandler(this));
		}

		return _escapedModelProxy;
	}

	@Override
	public Object clone() {
		TableFromDefaultDataSourceImpl tableFromDefaultDataSourceImpl = new TableFromDefaultDataSourceImpl();

		tableFromDefaultDataSourceImpl.setIFDDSId(getIFDDSId());
		tableFromDefaultDataSourceImpl.setDescription(getDescription());

		tableFromDefaultDataSourceImpl.resetOriginalValues();

		return tableFromDefaultDataSourceImpl;
	}

	public int compareTo(TableFromDefaultDataSource tableFromDefaultDataSource) {
		long primaryKey = tableFromDefaultDataSource.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TableFromDefaultDataSource tableFromDefaultDataSource = null;

		try {
			tableFromDefaultDataSource = (TableFromDefaultDataSource)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long primaryKey = tableFromDefaultDataSource.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<TableFromDefaultDataSource> toCacheModel() {
		TableFromDefaultDataSourceCacheModel tableFromDefaultDataSourceCacheModel =
			new TableFromDefaultDataSourceCacheModel();

		tableFromDefaultDataSourceCacheModel.IFDDSId = getIFDDSId();

		tableFromDefaultDataSourceCacheModel.Description = getDescription();

		String Description = tableFromDefaultDataSourceCacheModel.Description;

		if ((Description != null) && (Description.length() == 0)) {
			tableFromDefaultDataSourceCacheModel.Description = null;
		}

		return tableFromDefaultDataSourceCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{IFDDSId=");
		sb.append(getIFDDSId());
		sb.append(", Description=");
		sb.append(getDescription());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("com.meera.multidatasource.model.TableFromDefaultDataSource");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>IFDDSId</column-name><column-value><![CDATA[");
		sb.append(getIFDDSId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>Description</column-name><column-value><![CDATA[");
		sb.append(getDescription());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = TableFromDefaultDataSource.class.getClassLoader();
	private static Class<?>[] _escapedModelProxyInterfaces = new Class[] {
			TableFromDefaultDataSource.class
		};
	private long _IFDDSId;
	private String _Description;
	private TableFromDefaultDataSource _escapedModelProxy;
}