/**
 * Copyright (c) 2000-2012 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.meera.multidatasource.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TableFromDefaultDataSource service. Represents a row in the &quot;meera_TableFromDefaultDataSource&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.meera.multidatasource.model.impl.TableFromDefaultDataSourceModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.meera.multidatasource.model.impl.TableFromDefaultDataSourceImpl}.
 * </p>
 *
 * @author E5410
 * @see TableFromDefaultDataSource
 * @see com.meera.multidatasource.model.impl.TableFromDefaultDataSourceImpl
 * @see com.meera.multidatasource.model.impl.TableFromDefaultDataSourceModelImpl
 * @generated
 */
public interface TableFromDefaultDataSourceModel extends BaseModel<TableFromDefaultDataSource> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a table from default data source model instance should use the {@link TableFromDefaultDataSource} interface instead.
	 */

	/**
	 * Returns the primary key of this table from default data source.
	 *
	 * @return the primary key of this table from default data source
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this table from default data source.
	 *
	 * @param primaryKey the primary key of this table from default data source
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the i f d d s ID of this table from default data source.
	 *
	 * @return the i f d d s ID of this table from default data source
	 */
	public long getIFDDSId();

	/**
	 * Sets the i f d d s ID of this table from default data source.
	 *
	 * @param IFDDSId the i f d d s ID of this table from default data source
	 */
	public void setIFDDSId(long IFDDSId);

	/**
	 * Returns the description of this table from default data source.
	 *
	 * @return the description of this table from default data source
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this table from default data source.
	 *
	 * @param Description the description of this table from default data source
	 */
	public void setDescription(String Description);

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public Serializable getPrimaryKeyObj();

	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TableFromDefaultDataSource tableFromDefaultDataSource);

	public int hashCode();

	public CacheModel<TableFromDefaultDataSource> toCacheModel();

	public TableFromDefaultDataSource toEscapedModel();

	public String toString();

	public String toXmlString();
}